### ISSUE TITLE
Syncthing toggle does not persist restart

### ISSUE THREAD

**Issue by manzaloros** [spruceUI/spruceOS#37] opened 2024-09-09 15:06 UTC
Latest A30 firmware.
Spruce 2.2

- Turn the Syncthing toggle "on"
- Restart device 
- observe Syncthing toggle is "off"

The toggle does not persist restarting.

Is there some custom boot script that needs to be run to manually start Syncthing on every boot?

**Comment by spruceUI** [comment] 2024-09-09 22:16
Hmmm, indeed you are correct. I am not sure what happened here. It should stay ON. I'll mess with it and get back to you.

**Comment by spruceUI** [comment] 2024-09-09 22:24
[copy the contents of this into syncthingstatus in tmp_update-scripts.txt](https://github.com/user-attachments/files/16937210/copy.the.contents.of.this.into.syncthingstatus.in.tmp_update-scripts.txt)

Here is a file to get you by while i sort this out. open with Notepad syncthingstatus.sh in tmp_update/scripts and delete everything, copy/paste this in and save it.

It is just the old script from 2.0 and 2.1.

you will have an issue with the icon for Syncthing but it should function as intended.

**Comment by spruceUI** [comment] 2024-09-10 00:45
We found this issue and will fix it ASAP

**Comment by XanXic** [comment] 2024-09-10 03:00
Resolved with
https://github.com/spruceUI/spruceOS/pull/38

**Closed** 2024-09-10 02:59 UTC
Labels: bug
